name: "Test Environments"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, closed, synchronize]
permissions:
  contents: read
  pull-requests: write
  packages: read

jobs:
  run-tests:
    name: "Running Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
